apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: demo-guard
  labels:
    app: demo-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      automountServiceAccountToken: true
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "AKIADEMOINSECUREKEY"
            - name: AWS_SECRET_ACCESS_KEY
              value: "demo-hardcoded-secret-value"
