apiVersion: v1
kind: Pod
metadata:
  name: debug-privileged
  namespace: demo-guard
  labels:
    app: debug
spec:
  containers:
    - name: toolbox
      image: nicolaka/netshoot:latest
      command: ["sleep", "infinity"]
      securityContext:
        privileged: true
