apiVersion: v1
kind: Secret
metadata:
  name: demo-plain-secrets
  namespace: demo-guard
type: Opaque
stringData:
  DB_PASSWORD: "SuperInsecurePlaintextPassword123!"
  API_TOKEN: "hardcoded-demo-token-not-for-production"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-everything
  namespace: demo-guard
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
